run:
  name: llama3.1_405b
  results_dir: /results/
  time_limit: "0-02:30:00"
  dependency: "singleton"
trainer:
  num_nodes: 72
  devices: 8
  accelerator: gpu
  precision: bf16-mixed
  logger: false # logger provided by exp_manager
  enable_checkpointing: false
  use_distributed_sampler: false
  max_epochs: null
  max_steps: 100
  max_time: "05:23:30:00" # days:hours:minutes:seconds
  log_every_n_steps: 1
  val_check_interval: 100
  limit_val_batches: 1
  limit_test_batches: 50
  accumulate_grad_batches: 1
  gradient_clip_val: 1.0
  num_sanity_val_steps: 0
exp_manager:
  explicit_log_dir: /results/
  exp_dir: null
  name: megatron_llama
  create_wandb_logger: false
  wandb_logger_kwargs:
    project: nemo_llama_pretrain
    name: ${run.name}
  resume_if_exists: false
  resume_ignore_no_checkpoint: true
  create_checkpoint_callback: false
  checkpoint_callback_params:
    monitor: val_loss
    save_top_k: 10
    mode: min
    always_save_nemo: False # saves nemo file during validation, not implemented for model parallel
    save_nemo_on_train_end: False # not recommended when training large models on clusters with short time limits
    filename: 'megatron_llama--{val_loss:.2f}-{step}-{consumed_samples}'
    model_parallel_size: 72
  log_step_timing: true
  log_tflops_per_sec_per_gpu: false
  step_timing_kwargs:
    sync_cuda: true
    buffer_size: 5
  seconds_to_sleep: 60
model:
  mcore_gpt: true
  micro_batch_size: 1
  global_batch_size: 252
  rampup_batch_size: null
  tensor_model_parallel_size: 8
  pipeline_model_parallel_size: 9
  virtual_pipeline_model_parallel_size: 7
  context_parallel_size: 2
  encoder_seq_length: 8192
  max_position_embeddings: 8192
  num_layers: 126
  hidden_size: 16384
  ffn_hidden_size: 53248
  num_attention_heads: 128
  num_query_groups: 16
  init_method_std: 0.02
  use_scaled_init_method: true
  hidden_dropout: 0.0
  attention_dropout: 0.0
  ffn_dropout: 0.0
  kv_channels: null
  apply_query_key_layer_scaling: true
  normalization: rmsnorm
  layernorm_epsilon: 1.0e-05
  do_layer_norm_weight_decay: false
  make_vocab_size_divisible_by: 128
  pre_process: true
  post_process: true
  persist_layer_norm: true
  bias: false
  activation: fast-swiglu
  headscale: false
  transformer_block_type: pre_ln
  openai_gelu: false
  normalize_attention_scores: true
  position_embedding_type: rope
  rotary_percentage: 1.0
  apply_rope_fusion: true
  attention_type: multihead
  share_embeddings_and_output_weights: false
  scale_positional_embedding: true
  tokenizer:
    library: 'megatron'
    type: 'GPT2BPETokenizer'
    model: null
    delimiter: null # only used for tabular tokenizer
    vocab_file: ${data_dir}/vocab.json
    merge_file: ${data_dir}/merges.txt
  native_amp_init_scale: 4294967296
  native_amp_growth_interval: 1000
  hysteresis: 2
  fp32_residual_connection: false
  fp16_lm_cross_entropy: false
  megatron_amp_O2: true
  grad_allreduce_chunk_size_mb: 125
  grad_div_ar_fusion: true
  gradient_accumulation_fusion: true
  cross_entropy_loss_fusion: true
  bias_activation_fusion: true
  bias_dropout_add_fusion: true
  masked_softmax_fusion: true
  seed: 1234
  resume_from_checkpoint: null
  use_cpu_initialization: false
  onnx_safe: false
  apex_transformer_log_level: 30
  gradient_as_bucket_view: true
  sync_batch_comm: false
  activations_checkpoint_granularity: null
  activations_checkpoint_method: null
  activations_checkpoint_num_layers: null
  num_micro_batches_with_partial_activation_checkpoints: null
  activations_checkpoint_layers_per_pipeline: null
  sequence_parallel: true
  defer_embedding_wgrad_compute: true
  wgrad_deferral_limit: 50
  deterministic_mode: false
  transformer_engine: true
  fp8: False # enables fp8 in TransformerLayer forward
  fp8_e4m3: False # sets fp8_format = recipe.Format.E4M3
  fp8_hybrid: False # sets fp8_format = recipe.Format.HYBRID
  fp8_margin: 0 # scaling margin
  fp8_interval: 1 # scaling update interval
  fp8_amax_history_len: 1024 # Number of steps for which amax history is recorded per tensor
  fp8_amax_compute_algo: max # 'most_recent' or 'max'. Algorithm for computing amax from history
  ub_tp_comm_overlap: true
  use_flash_attention: true
  overlap_p2p_comm: true
  batch_p2p_comm: false
  gc_interval: 5
  nsys_profile:
    enabled: False
    trace: [nvtx,cuda]
    start_step: 10  # Global batch to start profiling
    end_step: 10 # Global batch to end profiling
    ranks: [0] # Global rank IDs to profile
    gen_shape: False # Generate model and kernel details including input shapes
  optim:
    name: distributed_fused_adam
    lr: 0.0003
    weight_decay: 0.1
    betas:
    - 0.9
    - 0.95
    bucket_cap_mb: 125
    overlap_grad_sync: true
    overlap_param_sync: true
    contiguous_grad_buffer: true
    contiguous_param_buffer: true
    sched:
      name: CosineAnnealing
      warmup_steps: 2000
      constant_steps: 0
      min_lr: 2.9999999999999997e-05
    grad_sync_dtype: bf16
  data:
    data_impl: mmap
    splits_string: 99990,8,2
    seq_length: 8192
    skip_warmup: true
    num_workers: 2
    dataloader_type: single
    reset_position_ids: false
    reset_attention_mask: false
    eod_mask_loss: false
    index_mapping_dir: null
    data_prefix:
    - .5
    - ${data_dir}/my-llama_00_text_document
    - .5
    - ${data_dir}/my-llama_01_text_document
  ub_tp_comm_overlap_cfg:
    fc1_dgrad:
      cga_size: 2
      method: bulk
      num_sm: 2
      set_sm_margin: 0
    fc1_fprop:
      aggregate: 1
      method: ring_exchange
      num_sm: 1
      set_sm_margin: 0
    fc1_wgrad:
      cga_size: 2
      method: bulk
      num_sm: 2
      set_sm_margin: 0
    fc2_dgrad:
      aggregate: 1
      method: ring_exchange
      num_sm: 1
      set_sm_margin: 0
    fc2_fprop:
      cga_size: 2
      fp8_buf: false
      method: pipeline
      num_sm: 8
      num_splits: 4
      set_sm_margin: 1
    proj_dgrad:
      aggregate: 1
      method: ring_exchange
      num_sm: 1
      set_sm_margin: 0
    proj_fprop:
      cga_size: 2
      fp8_buf: false
      method: pipeline
      num_sm: 24
      num_splits: 4
      set_sm_margin: 1
    qkv_dgrad:
      cga_size: 2
      method: bulk
      num_sm: 2
      set_sm_margin: 0
    qkv_fprop:
      aggregate: 1
      method: ring_exchange
      num_sm: 1
      set_sm_margin: 0
    qkv_wgrad:
      cga_size: 2
      method: bulk
      num_sm: 24
      set_sm_margin: 0
