---
- name: Create a multi-region network
  hosts: localhost
  vars:
    regions:
      - us-central1
      - us-east1
      - us-west1
      - europe-west1
    project: bacalhau-miscellaneous
    bucket_name: multi-region-example-bucket
    vm_group_label: bacalhau-multi-region-example
  tasks:
    - name: Create a bucket
      google.cloud.gcp_storage_bucket:
        name: "{{ bucket_name }}"
        project: "{{ project }}"
        auth_kind: application
        state: present
      register: bucket

    # - name: Print bucket info
    #   ansible.builtin.debug:
    #     var: bucket

    - name: Copy scripts to bucket
      ansible.builtin.copy:
        src: scripts/
        dest: "gs://{{ bucket.id }}/scripts"
        mode: "0700"

    - name: Create a private network
      google.cloud.gcp_compute_network:
        name: bac-ex-mr-network
        project: "{{ project }}"
        auth_kind: application
        auto_create_subnetworks: "true"
      register: bac_ex_mr_network

    - name: Create a rally point VM
      google.cloud.gcp_compute_instance:
        name: bacalhau-rally-point
        machine_type: n1-standard-4
        project: "{{ project }}"
        zone: "{{ regions[0] }}-a"
        network_interfaces:
          - network: "{{ bac_ex_mr_network }}"
            access_configs:
              - name: External NAT
                type: ONE_TO_ONE_NAT
        disks:
          - boot: true
            auto_delete: true
            size: 100
            initialize_params:
              image: projects/ubuntu-os-cloud/global/images/ubuntu-2204-jammy-v20230429
        metadata:
          startup-script-url: "gs://{{ bucket.id }}/scripts/install-bacalhau.sh"
        auth_kind: application
        labels:
          vm_name: bacalhau-rally-point
          vm_group_label: "{{ vm_group_label }}"

    # - name: Create a rally point VM
    #   google.cloud.gcp_compute_instance:
    #     name: rally-point
    #     machine_type: n1-standard-4
    #     zone: "{{ regions[0] }}a"
    #     network: "{{ bac_ex_mr_network.id }}"
    #     project: "{{ project }}"
    #     region: "{{ regions[0] }}"
    #     boot_disk:
    #       initialize_params:
    #         image: projects/ubuntu-os-cloud/global/images/family/ubuntu-22.04
    #     tags:
    #       - bacalhau-rally-point
    #       - "{{ vm_tags }}"

    - name: Add the bacalhau.service to systemd
      ansible.builtin.copy:
        src: scripts/bacalhau.service
        dest: /etc/systemd/system/bacalhau.service
        mode: "0700"

    # - name: Create three VMs
    #   google_compute_instance:
    #     name: "{{ item.name }}"
    #     machine_type: n1-standard-2
    #     zone: "{{ item.zone }}"
    #     network: "{{ network.id }}"
    #     project: "{{ project }}"
    #     region: "{{ item.region }}"
    #     boot_disk:
    #       initialize_params:
    #         image: projects/ubuntu-os-cloud/global/images/family/ubuntu-22.04
    #     tags:
    #       - bacalhau-vm
    #   loop:
    #     - name: "{{ item.zone }}-a-vm"
    #       zone: "{{ item.zone }}-a"
    #       region: "{{ item.region }}"
    #     - name: "{{ item.zone }}-b-vm"
    #       zone: "{{ item.zone }}-b"
    #       region: "{{ item.region }}"
    #     - name: "{{ item.zone }}-c-vm"
    #       zone: "{{ item.zone }}-c"
    #       region: "{{ item.region }}"

    # - name: Add the VMs to the private network
    #   google_compute_network_interface:
    #     network: "{{ network.id }}"
    #     subnetwork: "{{ network.default_subnetwork }}"
    #     name: "{{ item.name }}"
    #     project: "{{ project }}"
    #     region: "{{ item.region }}"
    #     instance: "{{ item.name }}"
    #     network_interface:
    #       network_ip: "{{ item.ip }}"
    #   loop: "{{ groups['all'] }}"
