# Sensor Simulator Configuration

sensor:
  id: "SENSOR001"
  type: "temperature_vibration"
  location: "Factory A - Machine 1"
  manufacturer: "SensorTech"
  model: "TempVibe-2025"
  firmware_version: "1.45"

simulation:
  readings_per_second: 1
  run_time_seconds: 86400 # a week

normal_parameters:
  temperature:
    mean: 65.0 # Celsius
    std_dev: 2.0
    min: 50.0
    max: 80.0
  vibration:
    mean: 2.5 # mm/s²
    std_dev: 0.5
    min: 0.1
    max: 10.0
  voltage:
    mean: 12.0 # Volts
    std_dev: 0.1
    min: 11.5
    max: 12.5

anomalies:
  enabled: true
  probability: 0.05 # 5% chance of anomaly per reading
  types:
    spike:
      enabled: true
      weight: 0.4
    trend:
      enabled: true
      weight: 0.2
      duration_seconds: 300 # 5 minutes
    pattern:
      enabled: true
      weight: 0.1
      duration_seconds: 600 # 10 minutes
    missing_data:
      enabled: true
      weight: 0.1
      duration_seconds: 30 # 30 seconds
    noise:
      enabled: true
      weight: 0.2
      duration_seconds: 180 # 3 minutes

database:
  path: "/app/data/sensor_data.db"
  backup_enabled: false
  backup_interval_hours: 24
  backup_path: "/app/data/backups/"
  batch_size: 100 # Number of readings to insert in a single batch

logging:
  level: "INFO"
  file: "/app/data/sensor_simulator.log"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  console_output: true

output:
  csv_export_enabled: false
  csv_export_path: "/app/data/exports/"
  csv_export_interval_minutes: 60

# Configuration for dynamic reloading
config_reload:
  enabled: true
  check_interval_seconds: 60

# Configuration for monitoring server
monitoring:
  enabled: true
  host: "0.0.0.0"
  port: 8080
  metrics_interval_seconds: 60
