name: config-reader
type: ops
constraints:
  - key: type
    operator: "="
    values:
      - "edge"
tasks:
  - name: main
    engine:
      type: wasm
      params:
        entryModule: /app/modules/config-reader.wasm
        entrypoint: "_start"
        parameters:
          - '--config={{or (index . "config") "/app/config.yaml"}}'
    inputSources:
      - source:
          type: localDirectory
          params:
            sourcePath: /app/
            readWrite: false
        target: /app/
