# permissions for end users to edit jobs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: job-editor-role
rules:
- apiGroups:
  - core.bacalhau.org
  resources:
  - bacalhaujobs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - core.bacalhau.org
  resources:
  - bacalhaujobs/status
  verbs:
  - get
