# Azure Cosmos DB Configuration Template
# Replace placeholder values with your actual configuration

cosmosdb:
  # Azure Cosmos DB endpoint URL
  endpoint: "https://your-cosmosdb-account.documents.azure.com:443/"

  # Primary key for authentication
  key: "your-primary-key-here"

  # Database name
  database: "log_analytics"

  # Container name for raw logs
  container: "raw_logs"

  # Partition key path (must include the leading slash)
  partition_key_path: "/region"

  # Connection settings
  connection:
    # Connection mode: "Gateway" or "Direct"
    mode: "Gateway"

    # Maximum number of retry attempts for operations
    max_retry_attempts: 9

    # Maximum retry wait time in seconds
    max_retry_wait_time_in_seconds: 30

    # Connection timeout in seconds
    connection_timeout: 60

    # Whether to enable endpoint discovery for multi-region accounts
    enable_endpoint_discovery: true

    # Preferred regions in order of preference (leave empty for default)
    preferred_regions: []

# Performance settings
performance:
  # Initial throughput in Request Units per second (RU/s)
  # For autoscale, this is the maximum throughput
  throughput: 10000

  # Whether to use autoscale throughput
  autoscale: true

  # Batch size for bulk operations
  batch_size: 1000

  # Maximum number of parallel operations
  max_parallel_operations: 10

  # Whether to disable indexing during bulk inserts (improves performance)
  disable_indexing_during_bulk: false

# Logging settings
logging:
  # Log level: DEBUG, INFO, WARNING, ERROR, CRITICAL
  level: "INFO"

  # Whether to log request units consumed
  log_request_units: true

  # Whether to log operation latency
  log_latency: true
