version: "3.8"

services:
  sensor-simulator:
    image: ghcr.io/bacalhau-project/sensor-simulator:latest
    pull_policy: always
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sensor-simulator
    restart: unless-stopped
    volumes:
      - ./logs:/var/log/app
      - ./config:/app/config
