services:
  sensor-simulator:
    image: ghcr.io/bacalhau-project/sensor-log-generator:2504151801
    pull_policy: always
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sensor-simulator
    restart: unless-stopped
    volumes:
      - ./logs:/var/log/app
      - ./config:/app/config
      - ./data:/app/data
