version: "3.8"
services:
  bacalhau-node:
    image: ghcr.io/bacalhau-project/bacalhau:latest
    privileged: true
    volumes:
      - type: bind
        source: ./orchestrator-config.yaml
        target: /etc/bacalhau/config.yaml
      - type: bind
        source: ./node-info
        target: /etc/node-info
    deploy:
      mode: replicated
      replicas: 3
