version: "3.8"
services:
  bacalhau-node:
    image: docker.io/bacalhauproject/bacalhau-dind-compute-node:2412211337
    privileged: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - type: bind
        source: ./orchestrator-config.yaml
        target: /etc/bacalhau/config.yaml
      - type: bind
        source: ./node-info
        target: /etc/node-info
    deploy:
      mode: replicated
      replicas: 3
