NameProvider: "uuid"
API:
  Port: 1234
Compute:
  Enabled: true
  Orchestrators:
    - nats://f503ee90-c4dc-4ac7-a7b5-a460aeb94fb3.us1.dev-cloud.expanso.dev:4222
  Auth:
    Token: "att3eiH8PWpazbFbiXv4tmXLnShzZky4kcJxW9T44r6wwpwB3ZBsnkvsqWsUpJa7"
  TLS:
    RequireTLS: true
  AllowListedLocalPaths:
    - /var/log/logs_to_process:rw
  Engine:
    Resources:
      CPU: 1
      Memory: 1GB
JobAdmissionControl:
  AcceptNetworkedJobs: true
