image: python:3.7

before_script:
  - python -V  # Print out python version for debugging

pages:
  script:
    - pip install -r requirements.txt
    - jupyter-book build how_to_eurec4a
    - mv how_to_eurec4a/_build/html/ public/
  artifacts:
    paths:
      - public
  only:
    - master

testbuild:
  script:
    - pip install -r requirements.txt
    - jupyter-book build how_to_eurec4a
  except:
    - master
