#######################################################################################
# A default configuration that will be loaded for all jupyter books
# See the documentation for help and more options:
# https://jupyterbook.org/customize/config.html

#######################################################################################
# Book settings
title                       : How to EUREC4A      # The title of the book. Will be placed in the left navbar.
author                      : EUREC4A community   # The author of the book
copyright                   : "2021"              # Copyright year to be placed in the footer
logo                        : logo_pyeurec4a.png  # A path to the book logo
repository:
  url                       : https://github.com/eurec4a/how_to_eurec4a
  path_to_book              : how_to_eurec4a
launch_buttons:
  binderhub_url             : https://mybinder.org
  thebe                     : true
  colab_url                 : https://colab.research.google.com
parse:
  myst_enable_extensions:
    - dollarmath
    - linkify
    - substitution
    - colon_fence
    - deflist
html:
  favicon                   : "logo_pyeurec4a.png" # A path to the favicon
  use_repository_button     : true
  use_issues_button         : true
  use_edit_page_button      : true
latex:
  latex_documents:
     targetname: how_to_eurec4a.tex
sphinx:
  local_extensions:
    apastyle: _ext/
    bracket_citation_style: _ext/
  config:
    latex_logo: logo_pyeurec4a.png
    latex_elements:
      preamble: \usepackage{how_to_eurec4a}
    latex_additional_files:
      - latex/how_to_eurec4a.sty
    bibtex_default_style: myapastyle
    bibtex_reference_style: author_year_round
execute:
  execute_notebooks         : cache
  timeout: 90
bibtex_reference_style      : author_year_round
bibtex_default_style        : myapastyle
bibtex_bibfiles             : references.bib
