apiVersion: core.bacalhau.org/v1
kind: BacalhauJob
metadata:
  name: simple-hello-world-1
  namespace: bacalhau-system
spec:
  entrypoint: 
    - "echo"
    - "hello"
    - "world"
  image: "alpine:latest"
  count: 2
  type: batch
