[project]
name = "sensor_manager"
version = "0.1.0"
description = "Sensor manager for Bacalhau examples"
requires-python = ">=3.11"
dependencies = [
    "pydantic>=2.0.0",
    "pyyaml>=6.0",
    "jinja2>=3.0.0",
    "docker>=6.0.0",
    "rich>=10.0.0",
]