[project]
name = "sensor_manager"
version = "0.1.0"
description = "Sensor manager for Bacalhau examples"
requires-python = ">=3.12"
dependencies = [
    "pydantic>=2.11.5",
    "pyyaml>=6.0.2",
    "jinja2>=3.1.6",
    "docker>=7.1.0",
    "rich>=14.0.0",
    "numpy>=2.2.6",
]
