version: "3.8"

services:
  log_generator:
    build:
      context: .
      dockerfile: Dockerfile
    image: docker.io/bacalhauproject/log-generator:2412152323

    # Mount log directories
    volumes:
      - ${LOGS_TO_PROCESS_DIR:-/var/log/logs_to_process}:/var/log/logs_to_process

    # Run log generator with configurable parameters
    command:
      - -d
      - ${LOGS_DIR:-/var/log/app}
      - -n
      - ${APP_NAME:-aperitivo}

    # Always restart container on failure
    restart: always

    # Environment variables with defaults
    environment:
      - TZ=UTC
      - APP_NAME=${APP_NAME:-aperitivo}
      - PYTHONUNBUFFERED=1
      - LOGS_DIR=/var/log/app
      - LOGS_TO_PROCESS_DIR=/var/log/logs_to_process

    # Set resource limits
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 128M
