services:
  bacalhau-node:
    image: ghcr.io/bacalhau-project/bacalhau:latest-dind
    privileged: true
    network_mode: host
    restart: always
    command:
      - "serve"
      - "--orchestrator"
      - "--config"
      - "/etc/bacalhau/config.yaml"
      - "-c"
      - "LABELS=${LABELS}"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - type: bind
        source: /bacalhau_node/config.yaml
        target: /etc/bacalhau/config.yaml
      - type: bind
        source: /bacalhau_node/node-info
        target: /etc/node-info
      - type: bind
        source: /bacalhau_data
        target: /bacalhau_data
