// Copyright (c) 2024 Expanso oss@expanso.io
// This software is licensed under the Apache2/MIT License.
// This was generated by Claude Sonnet 3.5, with the assistance of my human mentor

// bacalhau_client.go provides a client for interacting with the Bacalhau API server
// It's like a Swiss Army knife for distributed computing, but without the tiny scissors!

package utils

import (
	"math/rand"
	"time"
)

func GenerateID() string {
	return time.Now().Format("20060102150405") + "-" + RandomString(6)
}

func RandomString(n int) string {
	var letters = []rune("abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789")
	s := make([]rune, n)
	for i := range s {
		s[i] = letters[rand.Intn(len(letters))]
	}
	return string(s)
}
