# Access Log Generator Configuration
# All values are required

# Output settings
output:
  directory: /var/log/app # Where to store generated logs
  debug: false # Enable debug output
  pre_warm: false # Simulate 24 hours of traffic before starting
  rate: 2 # Logs per second (base rate before traffic patterns)

# State transition probabilities
state_transitions:
  START:
    LOGIN: 0.7 # Probability of going to login from start
    DIRECT_ACCESS: 0.3 # Probability of direct access without login
  LOGIN:
    BROWSING: 0.9 # Probability of successful login and browsing
    ABANDON: 0.1 # Probability of login abandonment
  DIRECT_ACCESS:
    BROWSING: 0.8 # Probability of continuing to browse
    LEAVE: 0.2 # Probability of leaving site
  BROWSING:
    LOGOUT: 0.4 # Probability of user logging out
    ABANDON: 0.3 # Probability of session abandonment
    ERROR: 0.05 # Probability of error occurring
    BROWSING: 0.25 # Probability of continuing to browse

# Page navigation weights
navigation:
  home:
    "/": 0.2 # Weight for staying on home page
    "/about": 0.3 # Weight for about page
    "/products": 0.4 # Weight for products page
    "/search": 0.1 # Weight for search page

# Error rates
error_rates:
  global_500: 0.02 # Probability of 500 error on any page
  product_404: 0.1 # Probability of 404 error on product pages
  cart_abandon: 0.5 # Probability of cart abandonment
  high_error_pages: # Pages with elevated error rates
    - path: "/products?categoryID=4"
      error_rate: 0.3
    - path: "/products?categoryID=5"
      error_rate: 0.3

# Session parameters
session:
  min_browsing_duration: 10 # Minimum session duration in seconds
  max_browsing_duration: 300 # Maximum session duration in seconds
  page_view_interval: 5 # Average time between page views in seconds

# Traffic patterns by time of day (Eastern Time)
traffic_patterns:
  - time: 2-6
    multiplier: 0.1 # Late night traffic multiplier
  - time: 6-9
    multiplier: 0.3 # Early morning traffic multiplier
  - time: 9-12
    multiplier: 0.7 # Late morning traffic multiplier
  - time: 12-15
    multiplier: 1.0 # Afternoon peak traffic multiplier
  - time: 15-18
    multiplier: 0.8 # Early evening traffic multiplier
  - time: 18-21
    multiplier: 0.5 # Dinner time traffic multiplier
  - time: 21-2
    multiplier: 0.2 # Night time traffic multiplier

# Sample user agent overrides (optional)
user_agents:
  desktop:
    - "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36"
    - "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.1 Safari/605.1.15"
  mobile:
    - "Mozilla/5.0 (iPhone; CPU iPhone OS 16_6 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.6 Mobile/15E148 Safari/604.1"
    - "Mozilla/5.0 (Linux; Android 13; SM-G991B) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Mobile Safari/537.36"

# Sample IP ranges (optional)
ip_ranges:
  - "192.168.1.0/24"
  - "10.0.0.0/8"
  - "172.16.0.0/12"

# Sample search terms (optional)
search_terms:
  - "shoes"
  - "laptop"
  - "phone"
  - "jacket"
  - "watch"
  - "headphones"
  - "camera"
  - "gaming"
  - "fitness"

# Sample product categories (optional)
product_categories:
  - "electronics"
  - "clothing"
  - "home"
  - "sports"
  - "books"
  - "toys"
  - "beauty"
  - "jewelry"
  - "furniture"

# Sample profile tabs (optional)
profile_tabs:
  - "orders"
  - "settings"
  - "payment"
  - "addresses"
  - "wishlist"
