Name: DeployLogstashConfig
Type: ops
Namespace: logging
Tasks:
  - Name: main
    Engine:
      Type: docker
      Params:
        Image: ubuntu:latest
        Entrypoint:
          - /bin/bash
        Parameters:
          - -c
          - mkdir -p /data/logstash-config && tar -xf /inputs/logstash-config.tar.gz -C /data/logstash-config && ls /data/logstash-config
    InputSources:
      - Target: /inputs
        Source:
          Type: s3
          Params:
            Bucket: bacalhaulogvending-bucket83908e77-ncvj2ymuvtgd
            Key: logstash-config.tar.gz
            Region: eu-west-1
      - Target: /data
        Source:
          Type: localDirectory
          Params:
            SourcePath: /data
            ReadWrite: true
