services:
  somanycars:
    image: ${DOCKER_IMAGE:-docker.io/bacalhauproject/somanycars-client:0.0.6}
    restart: "always"
    stop_grace_period: "3s"
    tty: true
    ports:
      - "${PORT:-14041}:14041"
    env_file:
      - path: default.env
        required: true
      - path: .env
        required: false
    volumes:
      - ${VIDEOSDIR:-./app/videos}:/app/videos
      - ${WEIGHTSDIR:-./app/weights}:/app/weights
      - ${LOGSDIR:-./app/logs}:/var/logs/uvicorn
      - ${CONFIGDIR:-./app/config}:/app/config
    deploy:
      resources:
        limits:
          cpus: "${DOCKER_WEB_CPUS:-0}"
          memory: "${DOCKER_WEB_MEMORY:-0}"
    healthcheck:
      test: "${DOCKER_WEB_HEALTHCHECK_TEST:-curl localhost:14041/ok}"
      interval: "60s"
      timeout: "3s"
      start_period: "5s"
      retries: 3
