name: bacalhau-network

x-common-env-variables: &common-env-variables
  BACALHAU_DISABLEANALYTICS: true
  LOG_LEVEL: info

# Common logging configuration to disable logs
x-logging-driver: &logging-driver
  logging:
    driver: "none"

services:
  orchestrator:
    image: ghcr.io/bacalhau-project/bacalhau:latest
    hostname: orchestrator
    command: serve -c /etc/bacalhau/config.yaml --name orchestrator
    environment: *common-env-variables
    ports:
      - "8438:8438"
      - "1234:1234"
      - "4222:4222"
    networks:
      - bacalhau-network
    volumes:
      - ./network-config/orchestrator.yaml:/etc/bacalhau/config.yaml
    deploy:
      resources:
        reservations:
          cpus: "2.0"
          memory: "4G"
    healthcheck:
      test: [ "CMD", "bacalhau", "agent", "alive" ]
      interval: 30s
      timeout: 20s
      retries: 10
      start_period: 15s
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
        compress: "false"

  nodes:
    image: ghcr.io/bacalhau-project/bacalhau:latest-dind
    privileged: true
    command: serve -c /etc/bacalhau/config.yaml
    volumes:
      - ./network-config/compute.yaml:/etc/bacalhau/config.yaml
      - ./docker-config/daemon.json:/etc/docker/daemon.json
    environment:
      <<: *common-env-variables
    depends_on:
      orchestrator:
        condition: service_healthy
    deploy:
      resources:
        limits:
          cpus: "0.50"
          memory: "200M" # 200MB per service
    networks:
      - bacalhau-network
    dns:
      - 1.1.1.1
    ulimits:
      nofile:
        soft: 4096
        hard: 4096
    <<: *logging-driver

  client:
    image: ghcr.io/bacalhau-project/bacalhau:latest
    entrypoint: /bin/sh
    stdin_open: true
    tty: true
    stop_signal: SIGTERM
    stop_grace_period: 3s
    environment:
      <<: *common-env-variables
      # Point to orchestrator on host network
      BACALHAU_API_HOST: "orchestrator"
    depends_on:
      - orchestrator
    networks:
      - bacalhau-network
    ulimits:
      nofile:
        soft: 4096
        hard: 4096
    <<: *logging-driver

networks:
  bacalhau-network:
    ipam:
      config:
        - subnet: 172.27.0.0/16
