max_instances: 5
username: bacalhau-runner
public_ssh_key_path: /root/.ssh/id_rsa.pub
compute_orchestrators:
  - nats://6hmm25qaoocs2b.us1.cloud.expanso.io:4222
compute_auth_token: Q3NjqKjhxEKQsiJuNYZp5K8KekWgdhmQiKPGDKpmU2Fs6EHJ5vbJPTVaMG5LwCv6
compute_tls: true
regions:
  - us-west-1:
      image: auto
      machine_type: m6gd.medium
      node_count: auto
