# AWS regions with spot instances suitable for Docker and containers
# This file is auto-generated by get_available_regions.py

AVAILABLE_REGIONS = [
    "ap-northeast-1",
    "ap-northeast-2",
    "ap-northeast-3",
    "ap-south-1",
    "ap-southeast-1",
    "ap-southeast-2",
    "ca-central-1",
    "eu-central-1",
    "eu-north-1",
    "eu-west-1",
    "eu-west-2",
    "eu-west-3",
    "sa-east-1",
    "us-east-1",
    "us-east-2",
    "us-west-1",
    "us-west-2",
]

# Detailed information about each region's smallest suitable instance
REGION_DETAILS = {
    "ap-northeast-3": {
        "instance_type": "t3.medium",
        "vcpus": 2,
        "memory_gib": 4.0,
        "spot_price": 0.019800,
    },
    "eu-north-1": {
        "instance_type": "c5d.large",
        "vcpus": 2,
        "memory_gib": 4.0,
        "spot_price": 0.024300,
    },
    "sa-east-1": {
        "instance_type": "m6gd.xlarge",
        "vcpus": 4,
        "memory_gib": 16.0,
        "spot_price": 0.045700,
    },
    "eu-west-3": {
        "instance_type": "m5ad.large",
        "vcpus": 2,
        "memory_gib": 8.0,
        "spot_price": 0.051400,
    },
    "ap-southeast-1": {
        "instance_type": "m5dn.large",
        "vcpus": 2,
        "memory_gib": 8.0,
        "spot_price": 0.057000,
    },
    "us-west-1": {
        "instance_type": "m5zn.large",
        "vcpus": 2,
        "memory_gib": 8.0,
        "spot_price": 0.058000,
    },
    "ap-south-1": {
        "instance_type": "m6gd.xlarge",
        "vcpus": 4,
        "memory_gib": 16.0,
        "spot_price": 0.062100,
    },
    "ap-northeast-2": {
        "instance_type": "m5zn.large",
        "vcpus": 2,
        "memory_gib": 8.0,
        "spot_price": 0.065500,
    },
    "ap-northeast-1": {
        "instance_type": "m5dn.large",
        "vcpus": 2,
        "memory_gib": 8.0,
        "spot_price": 0.070900,
    },
    "eu-central-1": {
        "instance_type": "m6gd.xlarge",
        "vcpus": 4,
        "memory_gib": 16.0,
        "spot_price": 0.071600,
    },
    "ap-southeast-2": {
        "instance_type": "m6gd.xlarge",
        "vcpus": 4,
        "memory_gib": 16.0,
        "spot_price": 0.074100,
    },
    "eu-west-2": {
        "instance_type": "m6gd.xlarge",
        "vcpus": 4,
        "memory_gib": 16.0,
        "spot_price": 0.074600,
    },
    "us-east-2": {
        "instance_type": "m6gd.xlarge",
        "vcpus": 4,
        "memory_gib": 16.0,
        "spot_price": 0.076600,
    },
    "ca-central-1": {
        "instance_type": "m6gd.xlarge",
        "vcpus": 4,
        "memory_gib": 16.0,
        "spot_price": 0.078100,
    },
    "us-west-2": {
        "instance_type": "m6gd.xlarge",
        "vcpus": 4,
        "memory_gib": 16.0,
        "spot_price": 0.082600,
    },
    "eu-west-1": {
        "instance_type": "m6gd.xlarge",
        "vcpus": 4,
        "memory_gib": 16.0,
        "spot_price": 0.091000,
    },
    "us-east-1": {
        "instance_type": "m6gd.xlarge",
        "vcpus": 4,
        "memory_gib": 16.0,
        "spot_price": 0.092800,
    },
}
