services:
  access-log-generator:
    image: ghcr.io/bacalhau-project/access-log-generator:latest
    pull_policy: always
    container_name: access-log-generator
    restart: unless-stopped
    volumes:
      - ./logs:/var/log/app
      - ./config:/app/config
    environment:
      - LOG_GENERATOR_CONFIG_PATH=/app/config/docker-config.yaml