# Use the docker:dind image as the base image
FROM docker:dind

# Set the working directory
WORKDIR /app

# Install curl and bash
RUN apk update && apk add --no-cache curl bash nano

# Install the ca-certificates package
RUN apk add --no-cache ca-certificates

# Copy a root ca into the image
COPY ./common_assets/certificates/generated_assets/bacalhau_test_root_ca.crt /usr/local/share/ca-certificates/bacalhau_test_root_ca.crt

# Update CA certificates
RUN update-ca-certificates

# Copy Assets
RUN mkdir -p /bacalhau_demo_assets
COPY ./common_assets/ /bacalhau_demo_assets
COPY ./common_assets/job-specs/job_anonymize_data.yaml /app/job_anonymize_data.yaml

# Download and execute the Bash script from the official URL
RUN curl -sSL https://get.bacalhau.org/install.sh | bash

# Download the minio cli binary, make it executable, and move it to /usr/local/bin
RUN curl -o /tmp/mc https://dl.min.io/client/mc/release/linux-amd64/mc \
    && chmod +x /tmp/mc \
    && mv /tmp/mc /usr/local/bin/

ENTRYPOINT ["dockerd-entrypoint.sh"]