# Ruff configuration for Databricks notebooks

[lint]
# Ignore star import warnings for PySpark (common in Databricks)
# E402: Module level import not at top of file
# E722: Do not use bare except
# F403: Star imports
# F405: May be undefined from star imports
# F821: Undefined name (for Databricks runtime objects)
ignore = ["F403", "F405", "E722", "E402", "F821"]

[lint.flake8-builtins]
# Assume these are available in Databricks runtime
builtins-ignorelist = ["dbutils", "spark", "display", "displayHTML"]