#cloud-config
packages:
  - git
  - make

write_files:
  - encoding: b64
    content: |
      ${ bacalhau_service }
    owner: root:root
    path: /etc/systemd/system/bacalhau.service
    permissions: "0600"
  - encoding: b64
    content: |
      ${ start_bacalhau }
    owner: root:root
    path: /node/start-bacalhau.sh
    permissions: "0700"

package_update: true

runcmd:
  - echo "Copying the SSH Key to the server"
  - |
    echo -n "${ ssh_key }" | awk 1 ORS=' ' >> /home/ubuntu/.ssh/authorized_keys
  # Set up directory structure and move files
  - sudo mkdir /node
  - sudo mkdir /data
  - sudo chmod +x /node/*.sh
  - sudo chmod 0700 /node
  - sudo chmod 0700 /data
  #
  # Install tailscale
  #
  - |
    sudo curl -fsSL "https://pkgs.tailscale.com/stable/ubuntu/jammy.noarmor.gpg" | sudo tee /usr/share/keyrings/tailscale-archive-keyring.gpg >/dev/null
    sudo curl -fsSL "https://pkgs.tailscale.com/stable/ubuntu/jammy.tailscale-keyring.list" | sudo tee /etc/apt/sources.list.d/tailscale.list
  - apt-get update -y
  - apt -y install tailscale
  - sudo tailscale up --authkey ${ tailscale_key } --hostname ${ node_name }
  #
  # Install go
  #
  - sudo rm -fr /usr/local/go /usr/local/bin/go
  - curl --silent --show-error --location --fail 'https://go.dev/dl/go1.20.4.linux-amd64.tar.gz' | sudo tar --extract --gzip --file=- --directory=/usr/local
  - sudo ln -s /usr/local/go/bin/go /usr/local/bin/go
  #
  # Install docker
  #
  - sudo apt-get install -y ca-certificates curl gnupg lsb-release
  - sudo mkdir -p /etc/apt/keyrings
  - |
    curl -fsSL "https://download.docker.com/linux/ubuntu/gpg" | sudo gpg --dearmor -o /etc/apt/keyrings/docker.gpg
    echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
  - sudo apt-get update -y
  - sudo apt -y install docker-ce docker-ce-cli containerd.io docker-compose-plugin
  #
  # Install git-lfs
  #
  - |
    curl -s "https://packagecloud.io/install/repositories/github/git-lfs/script.deb.sh" | sudo bash
  - sudo apt -y install git-lfs
  - HOME=/home/ubuntu git lfs install
  #
  # Install Bacalhau
  #
  # Can't use script until support for BACALHAU_PREFERRED_PEERS
  # - sudo chmod +x /node/install-bacalhau.sh
  # Build bacalhau
  - |
    git clone "https://github.com/bacalhau-project/bacalhau"
  - cd bacalhau
  - git checkout 2482-output-peering-information-to-run
  - HOME=/home/ubuntu make build
  - sudo mv bin/linux_amd64/bacalhau /usr/local/bin/bacalhau
  - sudo systemctl daemon-reload
  - sudo systemctl enable bacalhau.service
  - sudo systemctl restart bacalhau.service
