#cloud-config
package_update: true
package_upgrade: true

packages:
  - git
  - docker.io
  - jq

# Create user first
users:
  - name: ubuntu
    sudo: ALL=(ALL) NOPASSWD:ALL
    shell: /bin/bash
    groups: [docker, sudo]
    lock_passwd: true

runcmd:
  # Create directories and set permissions
  - echo "Creating directories..."
  - mkdir -p /etc/bacalhau
  - mkdir -p /usr/local/bin
  - mkdir -p /etc/systemd/system
  - mkdir -p /var/log/logs_to_process
  -
  - id ubuntu || echo "Ubuntu user not found"
  - chown -R ubuntu:ubuntu /etc/bacalhau || echo "Failed to set ownership on /etc/bacalhau"
  - chmod -R 755 /etc/bacalhau || echo "Failed to set permissions on /etc/bacalhau"

  # Write files manually since write_files module is failing
  - echo "Writing configuration files..."
  - echo "${orchestrator_config}" | base64 -d > /etc/bacalhau/config.yaml
  - chown ubuntu:ubuntu /etc/bacalhau/config.yaml
  - chmod 0600 /etc/bacalhau/config.yaml

  - echo "${bacalhau_service}" | base64 -d > /etc/systemd/system/bacalhau.service
  - chown root:root /etc/systemd/system/bacalhau.service
  - chmod 0644 /etc/systemd/system/bacalhau.service

  - echo "${start_bacalhau}" | base64 -d > /usr/local/bin/start_bacalhau.sh
  - chown root:root /usr/local/bin/start_bacalhau.sh
  - chmod 0755 /usr/local/bin/start_bacalhau.sh

  # Verify file creation and permissions
  - echo "Verifying file creation..."
  - ls -la /etc/systemd/system/bacalhau.service
  - cat /etc/systemd/system/bacalhau.service
  - ls -la /usr/local/bin/start_bacalhau.sh
  - cat /usr/local/bin/start_bacalhau.sh
  - ls -la /etc/bacalhau/config.yaml
  - cat /etc/bacalhau/config.yaml

  # Start Docker service
  - echo "Starting Docker service..."
  - systemctl start docker || echo "Failed to start Docker"
  - systemctl enable docker || echo "Failed to enable Docker"
  - systemctl status docker || echo "Docker status"

  # Install Bacalhau
  - echo "Installing Bacalhau..."
  - export BACALHAU_INSTALLATION_ID="${bacalhau_installation_id}"
  - curl -sL https://get.bacalhau.org/install.sh | bash -s -- -v pre-release -d /usr/local/bin || echo "Failed to install Bacalhau"
  - chmod +x /usr/local/bin/bacalhau || echo "Failed to make Bacalhau executable"
  - bacalhau version || echo "Failed to get Bacalhau version"

  # Start Bacalhau service
  - echo "Starting Bacalhau service..."
  - systemctl daemon-reload
  - systemctl enable bacalhau.service || echo "Failed to enable Bacalhau service"
  - systemctl start bacalhau.service || echo "Failed to start Bacalhau service"
  - systemctl status bacalhau.service || echo "Failed to get Bacalhau service status"
