resources:
- manager.yaml

generatorOptions:
  disableNameSuffixHash: true


configMapGenerator:
- files:
  - controller_manager_config.yaml
  name: manager-config
- literals:
  - APIHost=bootstrap.production.bacalhau.org
  - APIPort=1234
  name: api-config

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: job-controller-image
  newName: kdrezewski/bacalhau-job-controller
  newTag: 0.1.0
