simulation:
  readings_per_second: 10
  run_time_seconds: 360000 # 100 hours

normal_parameters:
  temperature:
    mean: 61.0 # Celsius
    std_dev: 2.0
    min: 50.0
    max: 80.0
  humidity:
    mean: 3.0 # Percentage
    std_dev: 0.5
    min: 0.0
    max: 100.0
  pressure:
    mean: 12.0 # Bar
    std_dev: 0.5
    min: 10.0
    max: 15.0
  voltage:
    mean: 12.0 # Volts
    std_dev: 0.1
    min: 11.5
    max: 12.5
  vibration:
    mean: 0.0 # Hz
    std_dev: 0.1
    min: 0.0
    max: 10.0

anomalies:
  enabled: true
  probability: 0.01
  types:
    spike:
      weight: 0.3
      duration_seconds: 60
    trend:
      weight: 0.2
      duration_seconds: 300
    pattern:
      weight: 0.2
      duration_seconds: 600
    missing_data:
      weight: 0.15
      duration_seconds: 30
    noise:
      weight: 0.15
      duration_seconds: 120

database:
  path: "/root/sensor_data.db"
  backup_enabled: false
  backup_interval_hours: 24
  backup_path: "/root/" # Backups will go directly into /root
  batch_size: 100 # Number of readings to insert in a single batch

logging:
  level: "INFO"
  file: "/root/sensor_simulator.log"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  console_output: true

# Configuration for dynamic reloading
dynamic_reloading:
  enabled: true
  check_interval_seconds: 5

# Configuration for monitoring server
monitoring:
  enabled: true
  host: "0.0.0.0"
  port: 8080
  metrics_interval_seconds: 60

# Configuration for location generation
random_location:
  enabled: true
  number_of_cities: 10
  gps_variation: 100 # meters
  cities_file: "/app/config/cities.json" # Config file, should be in config volume
