name: bacalhau-orchestrator

x-common-env-variables: &common-env-variables
  BACALHAU_DISABLEANALYTICS: true
  LOG_LEVEL: debug

services:
  orchestrator:
    image: ghcr.io/bacalhau-project/bacalhau:latest
    hostname: orchestrator
    command: serve -c /etc/bacalhau/config.yaml --name orchestrator
    environment: *common-env-variables
    ports:
      - "8438:8438"
      - "1234:1234"
      - "4222:4222"
    networks:
      - bacalhau-network
    volumes:
      - ./config/orchestrator.yaml:/etc/bacalhau/config.yaml
    healthcheck:
      test: ["CMD", "bacalhau", "agent", "alive"]
      interval: 30s
      timeout: 20s
      retries: 10
      start_period: 15s

  web-services:
    image: ghcr.io/bacalhau-project/bacalhau:latest-dind
    hostname: web-services
    command: serve -c /etc/bacalhau/config.yaml -c labels=type=web-services
    volumes:
      - ./config/compute.yaml:/etc/bacalhau/config.yaml
    environment:
      <<: *common-env-variables
      AWS_ACCESS_KEY_ID: "$AWS_ACCESS_KEY_ID"
      AWS_SECRET_ACCESS_KEY: "$AWS_SECRET_ACCESS_KEY"
    depends_on:
      orchestrator:
        condition: service_healthy
    privileged: true
    networks:
      - bacalhau-network

  sqs-puller:
    image: ghcr.io/bacalhau-project/event-puller:latest
    environment:
      <<: *common-env-variables
      AWS_ACCESS_KEY_ID: "$AWS_ACCESS_KEY_ID"
      AWS_SECRET_ACCESS_KEY: "$AWS_SECRET_ACCESS_KEY"
      AWS_REGION: "$AWS_REGION"
      SQS_QUEUE_URL: "$SQS_QUEUE_URL"
      ENV_FILE: /app/.env
    volumes:
      - ./.env:/app/.env
    networks:
      - bacalhau-network
    ports:
      - "8080:8080"

  client:
    image: ghcr.io/bacalhau-project/bacalhau:latest
    entrypoint: /bin/sh
    stdin_open: true
    tty: true
    stop_signal: SIGTERM
    stop_grace_period: 3s
    environment:
      <<: *common-env-variables
      BACALHAU_API_HOST: orchestrator
    depends_on:
      - orchestrator
    networks:
      - bacalhau-network

networks:
  bacalhau-network:
