services:
  bacalhau-node:
    image: ghcr.io/bacalhau-project/bacalhau:latest-dind
    privileged: true
    restart: always
    volumes:
      - type: bind
        source: /bacalhau_node/config.yaml
        target: /etc/bacalhau/config.yaml
      - type: bind
        source: /bacalhau_node/node-info
        target: /etc/node-info
      - type: bind
        source: /bacalhau_data
        target: /bacalhau_data
      - type: bind
        source: /mnt/data
        target: /mnt/data
    healthcheck:
      test: ["CMD", "curl", "-f", "localhost:1234"]
      interval: 2s
      timeout: 2s
      retries: 1
      start_period: 40s
    command:
      - "serve"
      - "--config"
      - "/etc/bacalhau/config.yaml"
      - "-c"
      - "Logging.Level=info"
      - "-c"
      - "LABELS=${LABELS}"
