version: '3'
services:
  log-generator:
    image: expanso/nginx-access-log-generator:latest
    command: ["--rate", "1", "--output-log-file", "/app/output/application.log"]
    volumes:
      - ~/loggen-output:/app/output:rw
  logstash:
    image: expanso/nginx-access-log-agent:latest
    env_file:
      - .env
    volumes:
      - ../../tools/logstash/:/app/state:rw
      - ~/loggen-output:/app/logs/:ro
    tty: true
    networks:
      - elk
    depends_on:
      - log-generator
networks:
  elk:
    external: true