name: Container Tests
on: [push, pull_request]

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest]  # Removed macos-latest as Docker containers require Linux runners
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3
        with:
          buildkitd-flags: --debug

      - name: Docker info
        run: |
          docker version
          docker info
          docker ps

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install UV
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
          echo "$HOME/.cargo/bin" >> $GITHUB_PATH

      - name: Run tests
        run: |
          cd tests/container
          sudo -E uv run --script test_container_orchestration.py -v --log-cli-level=DEBUG
