name: Container Tests
on:
  push:
    paths:
      - 'tests/container/**'
      - '.github/workflows/container-tests.yml'
  pull_request:
    paths:
      - 'tests/container/**'
      - '.github/workflows/container-tests.yml'

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest]  # Removed macos-latest as Docker containers require Linux runners
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3
        with:
          buildkitd-flags: --debug

      - name: Docker info
        run: |
          docker version
          docker info
          docker ps

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install UV
        run: |
          sudo mkdir -p /usr/local/uv
          curl -LsSf https://astral.sh/uv/install.sh | sudo CARGO_HOME=/usr/local/uv sh -s
          sudo mkdir -p /usr/local/uv/bin
          sudo mv /root/.local/bin/uv* /usr/local/uv/bin/
          sudo ln -sf /usr/local/uv/bin/uv /usr/local/bin/uv
          sudo chown -R root:root /usr/local/uv
          sudo chmod -R 755 /usr/local/uv

      - name: Run tests
        env:
          PYTHONPATH: ${{ github.workspace }}
        run: |
          cd tests/container
          sudo -E env "PATH=$PATH" "PYTHONPATH=$PYTHONPATH" uv pip install pytest pytest-timeout docker
          sudo -E env "PATH=$PATH" "PYTHONPATH=$PYTHONPATH" pytest -v --log-cli-level=DEBUG --tb=short -x --maxfail=1
