name: publish
on: [push]

jobs:
  publish:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v3
      - uses: cpina/github-action-push-to-another-repository@main
        env:
          SSH_DEPLOY_KEY: ${{ secrets.SSH_DEPLOY_KEY }}
        with:
          source-directory: "."
          destination-github-username: "bacalhau-project"
          destination-repository-name: "docs.bacalhau.org"
          user-email: examples@bacalhau-project
          target-branch: main
          target-directory: docs/examples
          commit-message: "bot(examples): ${{ github.event.head_commit.message }} via ${{ github.event.head_commit.url }}"
