name: publish
on: [push]

jobs:
  test-docusaurus:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Docs
        uses: actions/checkout@v3
        with:
          repository: ${{ github.repository_owner	 }}/docs.bacalhau.org
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: "16"
      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: $(yarn cache dir)"
          key: ${{ runner.os }}-node-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - run: yarn install --frozen-lockfile
      - run: yarn build

  publish:
    runs-on: ubuntu-latest
    needs: test-docusaurus
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v3
      - uses: cpina/github-action-push-to-another-repository@main
        env:
          SSH_DEPLOY_KEY: ${{ secrets.SSH_DEPLOY_KEY }}
        with:
          source-directory: "."
          destination-github-username: "bacalhau-project"
          destination-repository-name: "docs.bacalhau.org"
          user-email: examples@bacalhau-project
          target-branch: main
          target-directory: docs/examples
          commit-message: "bot(examples): ${{ github.event.head_commit.message }} via ${{ github.event.head_commit.url }}"
