name: test
on: [push]

jobs:
  test-ipynb:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - run: pip install nbmake
      - run: make test
